### ISSUE TITLE
Sorry to address the question.

### ISSUE THREAD

**Issue by maxtest404** [Pulse-Classic/Addon#18]
Sorry to address the question.
Recently I began to study the LUA language and I want to write a small add-on for the guild. I can’t understand how to display the table. In your addon, the table is displayed, but I can not understand how this is done. Could you help me? Please.

**Comment by tux-** [comment]
Not a bug: I am not sure what you mean by displayed. There is no UI in this addon. If you have troubble crating your own addon for wow, I would suggest the discord server for this.
